### ISSUE TITLE
Demo base mechanics

### ISSUE THREAD

**Issue by Tairesh** [Tairesh/midia#12]
# Combat
## Melee (#10)
- [x] basic attacks on distance 0
- [ ] attacks for spears and pikes with distance 1-2
- [x] "smash"-type attacks to items (for now it attacks only terrain, see furniture)
- [ ] "cut"-type attacks on some types of items
- [ ] weapons with minimum strenght
- [ ] attacks with allies (+1 to hit for every ally around)
- [ ] wearable buckler
- [ ] wieldable shield

## Ranged (#11)
- [ ] fire-type attacks (maybe spears should go here)
- [ ] throw-type attacks
- [ ] charges for weapons, arrows for example
- [ ] holster mechanic
- [ ] explode-type damage for grenades

# Inventory management
- [x] Wield items in left or right hand
- [x] Drop items
- [x] Wear items in different slots and layers
- [x] Display wielded items
- [ ] Display weared items
- [ ] Ability to take items off from wear
- [ ] View items in containers like backpack
- [ ] Ability to take items off from container
- [ ] Activate special uses of item in active hand (chop tree, dig, etc.)
- [ ] Pockets and things like holsters with fast (1 button) access to things inside

# Survival
- [ ] Basic food and drinks
- [ ] Mechanics to consume food and drinks from inventory
- [ ] Basic mechanic of hunger and thirst

# Worldgen
- [ ] Different chunks generators
- [ ] Encounters on a chunkmap

(unfinished)
